# Deployment for App A

apiVersion: apps/v1
kind: Deployment
metadata:
    name: 12factor-app-a-deployment
spec:
    selector:
        matchLabels:
            app: 12factor-app-a
    replicas: 2
    template:
        metadata:
            labels:
                app: 12factor-app-a
        spec:
            containers:
                - name: 12factor-app-a
                  image: liberty-service-a:1.0
                  ports:
                      - containerPort: 9080
                      - containerPort: 9443
                  env:
                      - name:  com_example_liberty_client_Service_mp_rest_url 
                        value: "http://factor-app-b-service:9081/data/client/service"
                      - name: conference
                        value: JAX London 2020
                  livenessProbe:
                      exec:
                          command: ["sh", "-c", "curl -s http://localhost:9080/health/live | grep -q live"]
                      initialDelaySeconds: 60
                  readinessProbe:
                      exec:
                          command: ["sh", "-c", "curl -s http://localhost:9080/health/ready | grep -q ready"]
                      initialDelaySeconds: 5
---

# Deployment for App B

apiVersion: apps/v1
kind: Deployment
metadata:
    name: 12factor-app-b-deployment
spec:
    selector:
        matchLabels:
            app: 12factor-app-b
    replicas: 2
    template:
        metadata:
            labels:
                app: 12factor-app-b
        spec:
            containers:
                - name: 12factor-app-b
                  image: liberty-service-b:1.0
                  ports:
                      - containerPort: 9081
                      - containerPort: 9444
                  
---

# Service for App A (exposes HTTP on port 30080)

apiVersion: v1
kind: Service
metadata:
  name: factor-app-a-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30080
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: 12factor-app-a
  type: NodePort
---

# Service for App B

apiVersion: v1
kind: Service
metadata:
  name: factor-app-b-service
spec:
  ports:
  - name: http
    port: 9081
    protocol: TCP
    targetPort: 9081
  - name: https
    port: 9444
    protocol: TCP
    targetPort: 9444
  selector:
    app: 12factor-app-b
  type: ClusterIP
